version: '3.3'
services:
  # marvellicious:
  #   container_name: docker-marvellicious
  #   build:
  #     context: ./
  #     dockerfile: ./marvellicious/Dockerfile
  #   ports:
  #     - "3102:3000"
  preact-pwa:
    image: "cheshirecode/docker-preact-pwa:${VERSION:-1.0}"
    container_name: "docker-preact-pwa"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3101:3100"
      - "3102:5000"